version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: "51X"
  ignore:
    - dependency-name: "System.Runtime.CompilerServices.Unsafe"
