name: Build dependants
on:
  push:
    branches:
      - '52X'
  pull_request:
    branches:
      - '52X'

jobs:
  Bizhawk52X:
    runs-on: windows-2022
    steps:
    # Checkout relevant code
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Checkout Bizhawk52X
      uses: actions/checkout@v2
      with:
        repository: 'redscientistlabs/Bizhawk52X-Vanguard'
        ref: 'main'
        path: 'Bizhawk52X-Vanguard'

    # Setup Tooling
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    # Restore packages for all targets
    - name: Restore packages in current build target
      run: msbuild /t:restore '.\RTCV\RTCV.sln'
    - name: Restore packages in Bizhawk
      run: msbuild /t:restore '.\Bizhawk52X-Vanguard\BizHawk.sln'

    # Build Bizhawk
    - name: Build Bizhawk52X-Vanguard
      run: msbuild '.\Bizhawk52X-Vanguard\BizHawk.sln'

  FileStub:
    runs-on: windows-2022
    steps:
    # Checkout relevant code
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Checkout FileStub
      uses: actions/checkout@v2
      with:
        repository: 'redscientistlabs/FileStub-Vanguard'
        ref: 'master'
        path: 'FileStub-Vanguard'

    # Setup Tooling
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    # Restore packages for all targets
    - name: Restore packages in current build target
      run: msbuild /t:restore '.\RTCV\RTCV.sln'
    - name: Restore packages in FileStub
      run: msbuild /t:restore '.\FileStub-Vanguard\FileStub-Vanguard.sln'

    # Build FileStub
    - name: Build FileStub-Vanguard
      run: msbuild '.\FileStub-Vanguard\FileStub-Vanguard.sln'

  ProcessStub:
    runs-on: windows-2022
    steps:
    # Checkout relevant code
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Checkout ProcessStub
      uses: actions/checkout@v2
      with:
        repository: 'redscientistlabs/ProcessStub-Vanguard'
        ref: 'master'
        path: 'ProcessStub-Vanguard'

    # Setup Tooling
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    # Restore packages for all targets
    - name: Restore packages in current build target
      run: msbuild /t:restore '.\RTCV\RTCV.sln'
    - name: Restore packages in ProcessStub
      run: msbuild /t:restore '.\ProcessStub-Vanguard\ProcessStub-Vanguard.sln'

    # Build ProcessStub
    - name: Build ProcessStub-Vanguard
      run: msbuild '.\ProcessStub-Vanguard\ProcessStub-Vanguard.sln'

  dolphin52X:
    runs-on: windows-2022
    steps:
    - name: Checkout dolphin
      uses: actions/checkout@v2
      with:
        repository: 'redscientistlabs/dolphin52X-vanguard'
        ref: 'Vanguard'
        path: 'dolphin52X-vanguard'
        submodules: 'true'
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Restore packages in RTCV
      run: msbuild /t:restore '.\RTCV\RTCV.sln'
    - name: Restore packages in dolphin52X-vanguard
      run: msbuild /t:restore '.\dolphin52X-vanguard\Source\dolphin-emu.sln'
    - name: Build with MSBuild
      run: msbuild '.\dolphin52X-vanguard\Source\dolphin-emu.sln' /property:Configuration=Release /property:Platform=x64 /p:TreatWarningAsError=false

  pcsx252X:
    runs-on: windows-2022
    # pcsx2 needs to cache dependencies and generate CMake before it can build
    if: ${{ false }}
    steps:
    - name: Checkout pcsx2
      uses: actions/checkout@v2
      with:
        repository: 'redscientistlabs/pcsx252X-Vanguard'
        ref: 'Vanguard'
        path: 'pcsx252X-Vanguard'
        submodules: 'true'
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Restore packages in RTCV
      run: msbuild /t:restore '.\RTCV\RTCV.sln'
    - name: Restore packages in pcsx252X-Vanguard
      run: msbuild /t:restore '.\pcsx252X-Vanguard\PCSX2_qt.sln'
    - name: Build with MSBuild
      run: msbuild '.\pcsx252X-Vanguard\PCSX2_qt.sln' /property:Configuration=Release /property:Platform=x64

  ppsspp52X:
    runs-on: windows-latest
    steps:
    - name: Checkout ppsspp
      uses: actions/checkout@v4
      with:
        repository: 'redscientistlabs/ppsspp52X-Vanguard'
        ref: 'Vanguard'
        path: 'ppsspp52X-Vanguard'
        submodules: 'recursive'
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Restore packages in RTCV
      run: msbuild /t:restore '.\RTCV\RTCV.sln'
    - name: Restore packages in ppsspp52X-Vanguard
      run: msbuild /t:restore '.\ppsspp52X-Vanguard\Windows\PPSSPP.sln'
    - name: Build with MSBuild
      run: msbuild '.\ppsspp52X-Vanguard\Windows\PPSSPP.sln' /property:Configuration=Release /property:Platform=x64

  flycast52X:
    runs-on: windows-2022
    # flycast needs to generate CMake before it can build
    if: ${{ false }}
    steps:
    - name: Checkout flycast
      uses: actions/checkout@v2
      with:
        repository: 'redscientistlabs/flycast52X-Vanguard'
        ref: 'Vanguard'
        path: 'flycast52X-Vanguard'
        submodules: 'true'
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'RTCV'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Restore packages in RTCV
      run: msbuild /t:restore '.\RTCV\RTCV.sln'
    - name: Restore packages in flycast52X-Vanguard
      run: msbuild /t:restore '.\flycast52X-Vanguard\build\flycast.sln'
    - name: Build with MSBuild
      run: msbuild '.\flycast52X-Vanguard\build\flycast.sln' /property:Configuration=Release /property:Platform=x64